# Generated by Django 3.2.16 on 2023-01-02 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spend_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 1, 2)),
        ),
    ]
