# Generated by Django 3.2.16 on 2023-01-02 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_expense_spend_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spend_date',
            field=models.DateField(default=datetime.date(2023, 1, 2)),
        ),
    ]
