# Generated by Django 3.2.16 on 2023-01-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_dayexpense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayExpense',
        ),
    ]
