# Generated by Django 3.2.16 on 2023-01-02 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_delete_dayexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrentExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_date', models.DateField(default=datetime.date(2023, 1, 3))),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-spend_date',),
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='spend_date',
            field=models.DateField(default=datetime.date(2023, 1, 3)),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 1, 3)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 1, 3)),
        ),
    ]
