# Generated by Django 3.2.16 on 2023-01-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_recurrentexpense_spend_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
